#!/bin/bash
mkdir -p tunnel_folder
cd tunnel_folder
wget -q https://raw.githubusercontent.com/CyberNetPlus/6to4-tunell/main/tunnel_wizard.sh -O tunnel_wizard.sh
chmod +x tunnel_wizard.sh
sudo bash tunnel_wizard.sh
